# Generated by Django 4.2.7 on 2023-12-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('user', 'user'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_google', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
