# Generated by Django 4.2.7 on 2024-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='Userprofiles/'),
        ),
    ]
