# Generated by Django 4.2.7 on 2023-12-06 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('streetaddress', models.TextField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zipcode', models.BigIntegerField(null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentprice', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('furnished_type', models.CharField(blank=True, choices=[('Fully Furnished', 'Fully Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('build_up_area', models.PositiveIntegerField(blank=True, null=True)),
                ('calendar_date', models.DateField(blank=True, null=True)),
                ('deposit_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Independent Floor', 'Independent Floor')], max_length=50)),
                ('bhk', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK')], max_length=50)),
                ('ownerinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.ownerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.post')),
            ],
        ),
    ]
