# Generated by Django 4.2.7 on 2023-12-22 15:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_to', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('furnished_type', models.CharField(max_length=50)),
                ('bhk_type', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('build_up_area', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_rent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('security_deposit', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.post')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('streetaddress', models.TextField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zipcode', models.BigIntegerField(null=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
