# Generated by Django 4.2.7 on 2023-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_post_ownerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
