# Generated by Django 4.2.7 on 2023-12-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_post_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='calendar_date',
            new_name='availableFrom',
        ),
    ]
