# Generated by Django 4.2.7 on 2023-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_rename_calendar_date_post_availablefrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bhk',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='furnished_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='property_type',
            field=models.CharField(max_length=50),
        ),
    ]
