# Generated by Django 4.2.7 on 2024-01-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_post_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_blocked',
            new_name='is_blocked_by_admin',
        ),
    ]
