# Generated by Django 4.2.7 on 2023-12-19 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0005_alter_post_bhk_alter_post_furnished_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='availableFrom',
            new_name='available_from',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bhk',
            new_name='bhk_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deposit_amount',
            new_name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ownerinfo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rentprice',
        ),
        migrations.AddField(
            model_name='post',
            name='house_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='locality',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='looking_to',
            field=models.CharField(default='Default House Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='security_deposit',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
