# Generated by Django 4.2.7 on 2024-01-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_rename_is_blocked_post_is_blocked_by_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerinfo',
            old_name='userId',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='is_verify',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='streetaddress',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='zipcode',
        ),
    ]
