# Generated by Django 4.2.7 on 2023-12-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_rename_availablefrom_post_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='furnished_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
