# Generated by Django 4.2.7 on 2024-01-19 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0006_rename_userid_ownerinfo_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerinfo',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='Ownerprofiles/'),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
