# Generated by Django 4.2.7 on 2024-01-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0007_rename_owner_name_ownerinfo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerinfo',
            name='owner',
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
