# Generated by Django 4.2.7 on 2024-01-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0008_remove_ownerinfo_owner_ownerinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerinfo',
            name='name',
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
