# Generated by Django 4.2.7 on 2024-01-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_remove_ownerinfo_name_alter_ownerinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='amenities',
            field=models.ManyToManyField(related_name='posts', to='owner.amenity'),
        ),
    ]
