# Generated by Django 4.2.7 on 2024-02-01 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_amenity_post_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='owner.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='amenities',
            field=models.ManyToManyField(related_name='posts_amenities', to='owner.amenity'),
        ),
    ]
