# Generated by Django 4.2.7 on 2024-02-01 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_amenity_post_alter_post_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenitie', to='owner.post'),
        ),
    ]
