# Generated by Django 4.2.7 on 2024-02-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_alter_amenity_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='long',
            field=models.CharField(default=0.0, max_length=50),
        ),
    ]
