# Generated by Django 4.2.7 on 2024-02-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_post_lat_post_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
