# Generated by Django 4.2.7 on 2023-11-22 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
        migrations.AddField(
            model_name='ownerdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
