# Generated by Django 4.2.7 on 2024-01-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackages',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
