# Generated by Django 4.2.7 on 2024-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_premiumpackages_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='premiumpackages',
            name='features',
        ),
        migrations.AddField(
            model_name='premiumpackages',
            name='features',
            field=models.ManyToManyField(blank=True, to='premium.feature'),
        ),
    ]
