# Generated by Django 4.2.7 on 2024-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_alter_premiumowner_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumowner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
