# Generated by Django 4.2.7 on 2024-02-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0006_alter_premiumowner_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpackages',
            name='validity',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
